server:
  port: 80

spring:
    application:
      name: springcloud-consumer
    thymeleaf:
            prefix: classpath:/templates/
            check-template-location: true
            suffix: .html
            encoding: UTF-8
            mode: LEGACYHTML5
            cache: false
    aop:
      auto: true
      proxy-target-class: true
    servlet:
          multipart:
            enabled: true
            max-file-size: 100000000
            max-request-size: 100000000
    main:
     allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2001/eureka/

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

logging:
  level:
    cn.luischen.dao : DEBUG

swagger:
  show: true

qiniu:
  accesskey: ""
  serectkey: ""
  bucket: ""
  cdn:
  url: ""